import type { NextPage } from "next";
import Head from "next/head";
import SessionPage from "../../src/pages/session_page";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>MEDBOX | Записи</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <SessionPage />
    </div>
  );
};
export default Home;
