import type { NextPage } from "next";
import Head from "next/head";
import MailPage from "../../src/pages/mail_page";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>MEDBOX | Почта</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <MailPage />
    </div>
  );
};
export default Home;
