import type { NextPage } from "next";
import Head from "next/head";
import ChatPage from "../../src/pages/chat_page";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>MEDBOX | Чат</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <ChatPage />
    </div>
  );
};
export default Home;
